/**
 * Printable region + PrintHeader / PrintFooter + ShareableSnapshotButton.
 *
 * Adopt on any surface that needs to be exported (printed, PDF'd, or
 * shared as a read-only signed URL):
 *
 *   <Printable
 *     header={<PrintHeader title="Decision Record" generatedAt={now} />}
 *     footer={<PrintFooter generatedBy={user.name} version={record.version} />}
 *   >
 *     <DecisionRecordBody ... />
 *   </Printable>
 *
 * The @ds/core print stylesheet at `tokens/print.css` keys off
 * `[data-print-target]` to hide app chrome and reflow this region for print.
 *
 * ShareableSnapshotButton mints a signed read-only URL via an injected
 * `onMintToken` async callback — @ds/core does not call the backend
 * itself; the consumer wires the mint endpoint (e.g. POST
 * /v1/shared-snapshots — filed as a separate backend ticket).
 */
import * as React from 'react';
import { Modal } from './Modal';

export interface PrintableProps {
  /** Optional header region (typically <PrintHeader>) */
  header?: React.ReactNode;
  /** Optional footer region (typically <PrintFooter>) */
  footer?: React.ReactNode;
  /** Export hint surfaced as a data-attribute for tooling/CSS. */
  exportFormat?: 'print' | 'pdf';
  /** Body content of the printable region. */
  children: React.ReactNode;
  className?: string;
}

export function Printable({
  header,
  footer,
  exportFormat = 'print',
  children,
  className,
}: PrintableProps) {
  return (
    <section
      className={['cc-printable', className].filter(Boolean).join(' ')}
      data-print-target=""
      data-export-format={exportFormat}
    >
      {header && <header className="cc-printable__header">{header}</header>}
      <div className="cc-printable__body">{children}</div>
      {footer && <footer className="cc-printable__footer">{footer}</footer>}
    </section>
  );
}

export interface PrintHeaderProps {
  /** Document title. */
  title: React.ReactNode;
  /** When the document was generated. Rendered as a <time> for provenance. */
  generatedAt?: Date;
  /** Optional org logo node (img / svg). */
  logo?: React.ReactNode;
  /** Current page within the printed output (1-based). */
  pageNumber?: number;
  /** Total page count of the printed output. */
  totalPages?: number;
}

export function PrintHeader({
  title,
  generatedAt,
  logo,
  pageNumber,
  totalPages,
}: PrintHeaderProps) {
  return (
    <div className="cc-print-header">
      {logo && <span className="cc-print-header__logo">{logo}</span>}
      <h1 className="cc-print-header__title">{title}</h1>
      <div className="cc-print-header__meta">
        {generatedAt && (
          <time
            className="cc-print-header__generated-at"
            dateTime={generatedAt.toISOString()}
            title={generatedAt.toISOString()}
          >
            {generatedAt.toISOString()}
          </time>
        )}
        {typeof pageNumber === 'number' && typeof totalPages === 'number' && (
          <span className="cc-print-header__pages">
            Page {pageNumber} of {totalPages}
          </span>
        )}
      </div>
    </div>
  );
}

export interface PrintFooterProps {
  /** Who generated the document (e.g. operator name or ID). */
  generatedBy: React.ReactNode;
  /** Document version (e.g. "v3.7" or a hash). */
  version?: React.ReactNode;
  /** Optional extra footer slot (e.g. confidentiality stamp). */
  extra?: React.ReactNode;
}

export function PrintFooter({ generatedBy, version, extra }: PrintFooterProps) {
  return (
    <div className="cc-print-footer">
      <span className="cc-print-footer__by">Generated by {generatedBy}</span>
      {version && (
        <span className="cc-print-footer__version">{version}</span>
      )}
      {extra && <span className="cc-print-footer__extra">{extra}</span>}
    </div>
  );
}

// ── ShareableSnapshotButton ─────────────────────────────────────────────────

export interface SnapshotMintRequest {
  /** Human-readable label for the resource being shared (audit + UI). */
  resourceLabel: string;
  /** Requested expiry in days (1–90). */
  expiryDays: number;
  /** Optional recipient email — captured for audit log. */
  recipientEmail?: string;
  /** Optional permission scope (free-form string the consumer interprets). */
  scope?: string;
}

export interface SnapshotMintResult {
  /** The signed read-only URL to share. */
  url: string;
  /** ISO timestamp the URL expires (provided by the mint endpoint). */
  expiresAt: string;
  /** Optional token id for audit/revocation. */
  tokenId?: string;
}

export interface ShareableSnapshotButtonProps {
  /** Callback to mint a token. Consumer wires this to the backend. */
  onMintToken: (req: SnapshotMintRequest) => Promise<SnapshotMintResult>;
  /** Resource label shown in the modal title. */
  resourceLabel: string;
  /** Default expiry in days when the modal opens. Default 14. */
  defaultExpiryDays?: number;
  /** Visible button label. Default 'Share read-only'. */
  label?: string;
  /** Called once the URL is generated; useful for analytics. */
  onMinted?: (result: SnapshotMintResult) => void;
  className?: string;
}

export function ShareableSnapshotButton({
  onMintToken,
  resourceLabel,
  defaultExpiryDays = 14,
  label = 'Share read-only',
  onMinted,
  className,
}: ShareableSnapshotButtonProps) {
  const [open, setOpen] = React.useState(false);
  const [expiryDays, setExpiryDays] = React.useState(defaultExpiryDays);
  const [recipientEmail, setRecipientEmail] = React.useState('');
  const [scope, setScope] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const [result, setResult] = React.useState<SnapshotMintResult | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  const reset = () => {
    setBusy(false);
    setResult(null);
    setError(null);
    setExpiryDays(defaultExpiryDays);
    setRecipientEmail('');
    setScope('');
  };

  const close = () => {
    setOpen(false);
    reset();
  };

  const mint = async () => {
    setBusy(true);
    setError(null);
    try {
      const r = await onMintToken({
        resourceLabel,
        expiryDays,
        recipientEmail: recipientEmail.trim() || undefined,
        scope: scope.trim() || undefined,
      });
      setResult(r);
      onMinted?.(r);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      <button
        type="button"
        className={['cc-btn', 'cc-btn--ghost', 'cc-snapshot-share-btn', className]
          .filter(Boolean)
          .join(' ')}
        onClick={() => setOpen(true)}
      >
        {label}
      </button>

      <Modal
        open={open}
        onClose={close}
        title={`Share read-only — ${resourceLabel}`}
        description="Generate a signed URL anyone with the link can open. Expires automatically."
        footer={
          <div className="cc-snapshot-share-footer">
            <button type="button" className="cc-btn cc-btn--ghost" onClick={close}>
              {result ? 'Done' : 'Cancel'}
            </button>
            {!result && (
              <button
                type="button"
                className="cc-btn cc-btn--primary"
                onClick={() => {
                  // eslint-disable-next-line @typescript-eslint/no-floating-promises
                  mint();
                }}
                disabled={busy}
              >
                {busy ? 'Generating…' : 'Generate link'}
              </button>
            )}
          </div>
        }
      >
        {!result && (
          <div className="cc-snapshot-share-form">
            <label className="cc-snapshot-share-field">
              Expires after
              <input
                type="number"
                min={1}
                max={90}
                value={expiryDays}
                onChange={(e) => setExpiryDays(Math.max(1, Math.min(90, Number(e.target.value) || 1)))}
              />
              <span>days</span>
            </label>
            <label className="cc-snapshot-share-field">
              Recipient email (optional, captured in audit log)
              <input
                type="email"
                value={recipientEmail}
                onChange={(e) => setRecipientEmail(e.target.value)}
                placeholder="auditor@example.com"
              />
            </label>
            <label className="cc-snapshot-share-field">
              Scope (optional)
              <input
                type="text"
                value={scope}
                onChange={(e) => setScope(e.target.value)}
                placeholder="evidence-bundle-readonly"
              />
            </label>
            {error && (
              <p className="cc-snapshot-share-error" role="alert">
                {error}
              </p>
            )}
          </div>
        )}
        {result && (
          <div className="cc-snapshot-share-result">
            <p>Share this URL — it expires on {new Date(result.expiresAt).toISOString()}.</p>
            <input
              type="text"
              readOnly
              value={result.url}
              aria-label="Generated shareable URL"
              onClick={(e) => (e.target as HTMLInputElement).select()}
            />
          </div>
        )}
      </Modal>
    </>
  );
}
